markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_name: DH Hub

extra_css:
  - stylesheets/colors.css
  - stylesheets/template-page.css
  - stylesheets/overrides.css

extra_javascript:
  - javascripts/extra.js

theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
    - content.code.copy
  palette:
    - scheme: orange

nav:
  - "index.md"
