name: update-site
run-name: Update site
on:
  push:
    tags:        
      - '*'
concurrency:
  group: update-site
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install jupyter mkdocs mkdocs-material
      - run: |
          git fetch --prune --unshallow --tags --force
          echo "Converting notebooks to HTML..."
          jupyter nbconvert ./**/**/**/notebook.ipynb --to html
          echo "Generating website..."
          cd website
          python generate-docs.py
          echo "Deploying with MkDocs..."
          cd generated
          mkdocs gh-deploy
          echo "Done."